[dependencies]
base = "https://github.com/dfinity/motoko-base#494824a2787aee24ab4a5888aa519deb05ecfd60"

[package]
name = "xtended-numbers"
version = "0.1.0"
description = "Extended functionality for motoko number types, such as byte encoding"
repository = "https://github.com/edjCase/motoko_numbers"