[dependencies]
base = "https://github.com/dfinity/motoko-base#aafcdee0c8328087aeed506e64aa2ff4ed329b47"

[package]
name = "xtended-numbers"
version = "0.1.0"
description = "Extended functionality for motoko number types, such as byte encoding"
repository = "https://github.com/edjCase/motoko_numbers"